<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Title>CountrySC</Title>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
	<PackageVersion>1.2.0</PackageVersion>
    <FileVersion></FileVersion>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>A lightweight library providing complete offline dataset of countries worldwide, ISO country codes, states, cities, currencies, spoken languages, flag svgs, capital cities,  and international dial codes</Description>
    <Copyright></Copyright>
    <PackageProjectUrl>https://github.com/marietta-a/countrysc</PackageProjectUrl>
    <RepositoryUrl>https://github.com/marietta-a/countrysc</RepositoryUrl>
    <PackageTags>countries; states; cities; country code; phone code; iso3166; timezone; timezones; language; languages; flags; flag icons; geolocation; geo; offline; continent; capital city; currency; currency iso; currency symbol; currency name</PackageTags>
    <Version>1.2.0</Version>
    <Authors>Marietta Akumbom</Authors>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="countries.json.br" Condition="Exists('countries.json.br')" />
    <EmbeddedResource Include="Assets\flags\*.svg" />
  </ItemGroup>

  <ItemGroup>
    <None Update="LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
