<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Title>csc</Title>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
	<PackageVersion>1.0.1</PackageVersion>
    <FileVersion></FileVersion>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>A lightweight .NET library providing a complete, offline dataset of countries, states/provinces, and cities — with ISO country codes, flag emojis, and international dial codes derived on the fly. No API calls, no network dependency;</Description>
    <Copyright></Copyright>
    <PackageProjectUrl>https://github.com/marietta-a/geolocation-data</PackageProjectUrl>
    <RepositoryUrl>https://github.com/marietta-a/geolocation-data</RepositoryUrl>
    <PackageTags>countries; states; cities; country code; phone code</PackageTags>
    <Version>1.0.1</Version>
    <Authors>Marietta</Authors>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="countries.json.br" Condition="Exists('countries.json.br')" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
