using System;
using System.Collections.Generic;

namespace CountrySC;

/// <summary>
/// Static lookup of currency details grouped by ISO 3166-1 alpha-2 country code.
/// Sourced from geocountries (https://www.geocountries.com/country/currencies).
/// </summary>
public static class CountryCurrencies
{
    public static readonly Dictionary<string, CountryCurrency> Currencies = new Dictionary<string, CountryCurrency>(StringComparer.OrdinalIgnoreCase)
    {
        { "AF", new CountryCurrency { Currency = "Afghan Afghani", Iso4217 = "AFN", Symbol = "؋" } },
        { "AX", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "AL", new CountryCurrency { Currency = "Albanian Lek", Iso4217 = "ALL", Symbol = "L" } },
        { "DZ", new CountryCurrency { Currency = "Algerian Dinar", Iso4217 = "DZD", Symbol = "د.ج" } },
        { "AS", new CountryCurrency { Currency = "United States Dollar", Iso4217 = "USD", Symbol = "$" } },
        { "AD", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "AO", new CountryCurrency { Currency = "Angolan Kwanza", Iso4217 = "AOA", Symbol = "Kz" } },
        { "AI", new CountryCurrency { Currency = "East Caribbean Dollar", Iso4217 = "XCD", Symbol = "$" } },
        { "AQ", new CountryCurrency { Currency = "", Iso4217 = "", Symbol = "" } },
        { "AG", new CountryCurrency { Currency = "East Caribbean Dollar", Iso4217 = "XCD", Symbol = "$" } },
        { "AR", new CountryCurrency { Currency = "Argentine Peso", Iso4217 = "ARS", Symbol = "$" } },
        { "AM", new CountryCurrency { Currency = "Armenian Dram", Iso4217 = "AMD", Symbol = "֏" } },
        { "AW", new CountryCurrency { Currency = "Aruban Florin", Iso4217 = "AWG", Symbol = "ƒ" } },
        { "AU", new CountryCurrency { Currency = "Australian Dollar", Iso4217 = "AUD", Symbol = "$" } },
        { "AT", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "AZ", new CountryCurrency { Currency = "Azerbaijani Manat", Iso4217 = "AZN", Symbol = "₼" } },
        { "BS", new CountryCurrency { Currency = "Bahamian Dollar", Iso4217 = "BSD", Symbol = "$" } },
        { "BH", new CountryCurrency { Currency = "Bahraini Dinar", Iso4217 = "BHD", Symbol = ".د.ب" } },
        { "BD", new CountryCurrency { Currency = "Bangladeshi Taka", Iso4217 = "BDT", Symbol = "৳" } },
        { "BB", new CountryCurrency { Currency = "Barbadian Dollar", Iso4217 = "BBD", Symbol = "$" } },
        { "BY", new CountryCurrency { Currency = "Belarusian Ruble", Iso4217 = "BYN", Symbol = "Br" } },
        { "BE", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "BZ", new CountryCurrency { Currency = "Belize Dollar", Iso4217 = "BZD", Symbol = "$" } },
        { "BJ", new CountryCurrency { Currency = "West African CFA Franc", Iso4217 = "XOF", Symbol = "Fr" } },
        { "BM", new CountryCurrency { Currency = "Bermudian Dollar", Iso4217 = "BMD", Symbol = "$" } },
        { "BT", new CountryCurrency { Currency = "Bhutanese Ngultrum", Iso4217 = "BTN", Symbol = "Nu." } },
        { "BO", new CountryCurrency { Currency = "Bolivian Boliviano", Iso4217 = "BOB", Symbol = "Bs." } },
        { "BQ", new CountryCurrency { Currency = "United States Dollar", Iso4217 = "USD", Symbol = "$" } },
        { "BA", new CountryCurrency { Currency = "Bosnia And Herzegovina Convertible Mark", Iso4217 = "BAM", Symbol = "KM" } },
        { "BW", new CountryCurrency { Currency = "Botswana Pula", Iso4217 = "BWP", Symbol = "P" } },
        { "BV", new CountryCurrency { Currency = "Norwegian Krone", Iso4217 = "NOK", Symbol = "kr" } },
        { "BR", new CountryCurrency { Currency = "Brazilian Real", Iso4217 = "BRL", Symbol = "R$" } },
        { "IO", new CountryCurrency { Currency = "United States Dollar", Iso4217 = "USD", Symbol = "$" } },
        { "BN", new CountryCurrency { Currency = "Brunei Dollar", Iso4217 = "BND", Symbol = "$" } },
        { "BG", new CountryCurrency { Currency = "Bulgarian Lev", Iso4217 = "BGN", Symbol = "лв" } },
        { "BF", new CountryCurrency { Currency = "West African CFA Franc", Iso4217 = "XOF", Symbol = "Fr" } },
        { "BI", new CountryCurrency { Currency = "Burundian Franc", Iso4217 = "BIF", Symbol = "Fr" } },
        { "KH", new CountryCurrency { Currency = "Cambodian Riel", Iso4217 = "KHR", Symbol = "៛" } },
        { "CM", new CountryCurrency { Currency = "Central African CFA Franc", Iso4217 = "XAF", Symbol = "Fr" } },
        { "CA", new CountryCurrency { Currency = "Canadian Dollar", Iso4217 = "CAD", Symbol = "$" } },
        { "CV", new CountryCurrency { Currency = "Cape Verdean Escudo", Iso4217 = "CVE", Symbol = "Esc" } },
        { "KY", new CountryCurrency { Currency = "Cayman Islands Dollar", Iso4217 = "KYD", Symbol = "$" } },
        { "CF", new CountryCurrency { Currency = "Central African CFA Franc", Iso4217 = "XAF", Symbol = "Fr" } },
        { "TD", new CountryCurrency { Currency = "Central African CFA Franc", Iso4217 = "XAF", Symbol = "Fr" } },
        { "CL", new CountryCurrency { Currency = "Chilean Peso", Iso4217 = "CLP", Symbol = "$" } },
        { "CN", new CountryCurrency { Currency = "Chinese Yuan", Iso4217 = "CNY", Symbol = "¥" } },
        { "CX", new CountryCurrency { Currency = "Australian Dollar", Iso4217 = "AUD", Symbol = "$" } },
        { "CC", new CountryCurrency { Currency = "Australian Dollar", Iso4217 = "AUD", Symbol = "$" } },
        { "CO", new CountryCurrency { Currency = "Colombian Peso", Iso4217 = "COP", Symbol = "$" } },
        { "KM", new CountryCurrency { Currency = "Comorian Franc", Iso4217 = "KMF", Symbol = "Fr" } },
        { "CG", new CountryCurrency { Currency = "Central African CFA Franc", Iso4217 = "XAF", Symbol = "Fr" } },
        { "CD", new CountryCurrency { Currency = "Congolese Franc", Iso4217 = "CDF", Symbol = "Fr" } },
        { "CK", new CountryCurrency { Currency = "Cook Islands Dollar", Iso4217 = "CKD", Symbol = "$" } },
        { "CR", new CountryCurrency { Currency = "Costa Rican Colón", Iso4217 = "CRC", Symbol = "₡" } },
        { "CI", new CountryCurrency { Currency = "West African CFA Franc", Iso4217 = "XOF", Symbol = "Fr" } },
        { "HR", new CountryCurrency { Currency = "Croatian Kuna", Iso4217 = "HRK", Symbol = "kn" } },
        { "CU", new CountryCurrency { Currency = "Cuban Peso", Iso4217 = "CUP", Symbol = "$" } },
        { "CW", new CountryCurrency { Currency = "Netherlands Antillean Guilder", Iso4217 = "ANG", Symbol = "ƒ" } },
        { "CY", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "CZ", new CountryCurrency { Currency = "Czech Koruna", Iso4217 = "CZK", Symbol = "Kč" } },
        { "DK", new CountryCurrency { Currency = "Danish Krone", Iso4217 = "DKK", Symbol = "kr" } },
        { "DJ", new CountryCurrency { Currency = "Djiboutian Franc", Iso4217 = "DJF", Symbol = "Fr" } },
        { "DM", new CountryCurrency { Currency = "East Caribbean Dollar", Iso4217 = "XCD", Symbol = "$" } },
        { "DO", new CountryCurrency { Currency = "Dominican Peso", Iso4217 = "DOP", Symbol = "$" } },
        { "TL", new CountryCurrency { Currency = "United States Dollar", Iso4217 = "USD", Symbol = "$" } },
        { "EC", new CountryCurrency { Currency = "United States Dollar", Iso4217 = "USD", Symbol = "$" } },
        { "EG", new CountryCurrency { Currency = "Egyptian Pound", Iso4217 = "EGP", Symbol = "E£" } },
        { "SV", new CountryCurrency { Currency = "United States Dollar", Iso4217 = "USD", Symbol = "$" } },
        { "GQ", new CountryCurrency { Currency = "Central African CFA Franc", Iso4217 = "XAF", Symbol = "Fr" } },
        { "ER", new CountryCurrency { Currency = "Eritrean Nakfa", Iso4217 = "ERN", Symbol = "Nfk" } },
        { "EE", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "ET", new CountryCurrency { Currency = "Ethiopian Birr", Iso4217 = "ETB", Symbol = "Br" } },
        { "FK", new CountryCurrency { Currency = "Falkland Islands Pound", Iso4217 = "FKP", Symbol = "£" } },
        { "FO", new CountryCurrency { Currency = "Danish Krone", Iso4217 = "DKK", Symbol = "kr" } },
        { "FJ", new CountryCurrency { Currency = "Fijian Dollar", Iso4217 = "FJD", Symbol = "$" } },
        { "FI", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "FR", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "GF", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "PF", new CountryCurrency { Currency = "CFP Franc", Iso4217 = "XPF", Symbol = "Fr" } },
        { "TF", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "GA", new CountryCurrency { Currency = "Central African CFA Franc", Iso4217 = "XAF", Symbol = "Fr" } },
        { "GM", new CountryCurrency { Currency = "Gambian Dalasi", Iso4217 = "GMD", Symbol = "D" } },
        { "GE", new CountryCurrency { Currency = "Georgian Lari", Iso4217 = "GEL", Symbol = "₾" } },
        { "DE", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "GH", new CountryCurrency { Currency = "Ghanaian Cedi", Iso4217 = "GHS", Symbol = "₵" } },
        { "GI", new CountryCurrency { Currency = "Gibraltar Pound", Iso4217 = "GIP", Symbol = "£" } },
        { "GR", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "GL", new CountryCurrency { Currency = "Danish Krone", Iso4217 = "DKK", Symbol = "kr" } },
        { "GD", new CountryCurrency { Currency = "East Caribbean Dollar", Iso4217 = "XCD", Symbol = "$" } },
        { "GP", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "GU", new CountryCurrency { Currency = "United States Dollar", Iso4217 = "USD", Symbol = "$" } },
        { "GT", new CountryCurrency { Currency = "Guatemalan Quetzal", Iso4217 = "GTQ", Symbol = "Q" } },
        { "GG", new CountryCurrency { Currency = "Guernsey Pound", Iso4217 = "GGP", Symbol = "£" } },
        { "GN", new CountryCurrency { Currency = "Guinean Franc", Iso4217 = "GNF", Symbol = "Fr" } },
        { "GW", new CountryCurrency { Currency = "West African CFA Franc", Iso4217 = "XOF", Symbol = "Fr" } },
        { "GY", new CountryCurrency { Currency = "Guyanese Dollar", Iso4217 = "GYD", Symbol = "$" } },
        { "HT", new CountryCurrency { Currency = "Haitian Gourde", Iso4217 = "HTG", Symbol = "G" } },
        { "HM", new CountryCurrency { Currency = "Australian Dollar", Iso4217 = "AUD", Symbol = "$" } },
        { "HN", new CountryCurrency { Currency = "Honduran Lempira", Iso4217 = "HNL", Symbol = "L" } },
        { "HK", new CountryCurrency { Currency = "Hong Kong Dollar", Iso4217 = "HKD", Symbol = "$" } },
        { "HU", new CountryCurrency { Currency = "Hungarian Forint", Iso4217 = "HUF", Symbol = "Ft" } },
        { "IS", new CountryCurrency { Currency = "Icelandic Krona", Iso4217 = "ISK", Symbol = "kr" } },
        { "IN", new CountryCurrency { Currency = "Indian Rupee", Iso4217 = "INR", Symbol = "₹" } },
        { "ID", new CountryCurrency { Currency = "Indonesian Rupiah", Iso4217 = "IDR", Symbol = "Rp" } },
        { "IR", new CountryCurrency { Currency = "Iranian Rial", Iso4217 = "IRR", Symbol = "﷼" } },
        { "IQ", new CountryCurrency { Currency = "Iraqi Dinar", Iso4217 = "IQD", Symbol = "ع.د" } },
        { "IE", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "IL", new CountryCurrency { Currency = "Israeli New Shekel", Iso4217 = "ILS", Symbol = "₪" } },
        { "IT", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "JM", new CountryCurrency { Currency = "Jamaican Dollar", Iso4217 = "JMD", Symbol = "$" } },
        { "JP", new CountryCurrency { Currency = "Japanese Yen", Iso4217 = "JPY", Symbol = "¥" } },
        { "JE", new CountryCurrency { Currency = "Jersey Pound", Iso4217 = "JEP", Symbol = "£" } },
        { "JO", new CountryCurrency { Currency = "Jordanian Dinar", Iso4217 = "JOD", Symbol = "د.ا" } },
        { "KZ", new CountryCurrency { Currency = "Kazakhstani Tenge", Iso4217 = "KZT", Symbol = "₸" } },
        { "KE", new CountryCurrency { Currency = "Kenyan Shilling", Iso4217 = "KES", Symbol = "Sh" } },
        { "KI", new CountryCurrency { Currency = "Australian Dollar", Iso4217 = "AUD", Symbol = "$" } },
        { "KP", new CountryCurrency { Currency = "North Korean Won", Iso4217 = "KPW", Symbol = "₩" } },
        { "KR", new CountryCurrency { Currency = "South Korean Won", Iso4217 = "KRW", Symbol = "₩" } },
        { "XK", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "KW", new CountryCurrency { Currency = "Kuwaiti Dinar", Iso4217 = "KWD", Symbol = "د.ك" } },
        { "KG", new CountryCurrency { Currency = "Kyrgyzstani Som", Iso4217 = "KGS", Symbol = "c" } },
        { "LA", new CountryCurrency { Currency = "Lao Kip", Iso4217 = "LAK", Symbol = "₭" } },
        { "LV", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "LB", new CountryCurrency { Currency = "Lebanese Pound", Iso4217 = "LBP", Symbol = "ل.ل" } },
        { "LS", new CountryCurrency { Currency = "Lesotho Loti", Iso4217 = "LSL", Symbol = "L" } },
        { "LR", new CountryCurrency { Currency = "Liberian Dollar", Iso4217 = "LRD", Symbol = "$" } },
        { "LY", new CountryCurrency { Currency = "Libyan Dinar", Iso4217 = "LYD", Symbol = "ل.د" } },
        { "LI", new CountryCurrency { Currency = "Swiss Franc", Iso4217 = "CHF", Symbol = "Fr" } },
        { "LT", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "LU", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "MO", new CountryCurrency { Currency = "Macanese Pataca", Iso4217 = "MOP", Symbol = "P" } },
        { "MK", new CountryCurrency { Currency = "North Macedonian Denar", Iso4217 = "MKD", Symbol = "ден" } },
        { "MG", new CountryCurrency { Currency = "Malagasy Ariary", Iso4217 = "MGA", Symbol = "Ar" } },
        { "MW", new CountryCurrency { Currency = "Malawian Kwacha", Iso4217 = "MWK", Symbol = "MK" } },
        { "MY", new CountryCurrency { Currency = "Malaysian Ringgit", Iso4217 = "MYR", Symbol = "RM" } },
        { "MV", new CountryCurrency { Currency = "Maldivian Rufiyaa", Iso4217 = "MVR", Symbol = ".ރ" } },
        { "ML", new CountryCurrency { Currency = "West African CFA Franc", Iso4217 = "XOF", Symbol = "Fr" } },
        { "MT", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "IM", new CountryCurrency { Currency = "Manx Pound", Iso4217 = "IMP", Symbol = "£" } },
        { "MH", new CountryCurrency { Currency = "United States Dollar", Iso4217 = "USD", Symbol = "$" } },
        { "MQ", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "MR", new CountryCurrency { Currency = "Mauritanian Ouguiya", Iso4217 = "MRU", Symbol = "UM" } },
        { "MU", new CountryCurrency { Currency = "Mauritian Rupee", Iso4217 = "MUR", Symbol = "₨" } },
        { "YT", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "MX", new CountryCurrency { Currency = "Mexican Peso", Iso4217 = "MXN", Symbol = "$" } },
        { "FM", new CountryCurrency { Currency = "United States Dollar", Iso4217 = "USD", Symbol = "$" } },
        { "MD", new CountryCurrency { Currency = "Moldovan Leu", Iso4217 = "MDL", Symbol = "L" } },
        { "MC", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "MN", new CountryCurrency { Currency = "Mongolian Togrog", Iso4217 = "MNT", Symbol = "₮" } },
        { "ME", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "MS", new CountryCurrency { Currency = "East Caribbean Dollar", Iso4217 = "XCD", Symbol = "$" } },
        { "MA", new CountryCurrency { Currency = "Moroccan Dirham", Iso4217 = "MAD", Symbol = "د.م." } },
        { "MZ", new CountryCurrency { Currency = "Mozambican Metical", Iso4217 = "MZN", Symbol = "MT" } },
        { "MM", new CountryCurrency { Currency = "Burmese Kyat", Iso4217 = "MMK", Symbol = "Ks" } },
        { "NA", new CountryCurrency { Currency = "Namibian Dollar", Iso4217 = "NAD", Symbol = "$" } },
        { "NR", new CountryCurrency { Currency = "Australian Dollar", Iso4217 = "AUD", Symbol = "$" } },
        { "NP", new CountryCurrency { Currency = "Nepalese Rupee", Iso4217 = "NPR", Symbol = "₨" } },
        { "NL", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "NC", new CountryCurrency { Currency = "CFP Franc", Iso4217 = "XPF", Symbol = "Fr" } },
        { "NZ", new CountryCurrency { Currency = "New Zealand Dollar", Iso4217 = "NZD", Symbol = "$" } },
        { "NI", new CountryCurrency { Currency = "Nicaraguan Cordoba", Iso4217 = "NIO", Symbol = "C$" } },
        { "NE", new CountryCurrency { Currency = "West African CFA Franc", Iso4217 = "XOF", Symbol = "Fr" } },
        { "NG", new CountryCurrency { Currency = "Nigerian Naira", Iso4217 = "NGN", Symbol = "₦" } },
        { "NU", new CountryCurrency { Currency = "New Zealand Dollar", Iso4217 = "NZD", Symbol = "$" } },
        { "NF", new CountryCurrency { Currency = "Australian Dollar", Iso4217 = "AUD", Symbol = "$" } },
        { "MP", new CountryCurrency { Currency = "United States Dollar", Iso4217 = "USD", Symbol = "$" } },
        { "NO", new CountryCurrency { Currency = "Norwegian Krone", Iso4217 = "NOK", Symbol = "kr" } },
        { "OM", new CountryCurrency { Currency = "Omani Rial", Iso4217 = "OMR", Symbol = "ر.ع." } },
        { "PK", new CountryCurrency { Currency = "Pakistani Rupee", Iso4217 = "PKR", Symbol = "₨" } },
        { "PW", new CountryCurrency { Currency = "United States Dollar", Iso4217 = "USD", Symbol = "$" } },
        { "PS", new CountryCurrency { Currency = "Israeli New Shekel", Iso4217 = "ILS", Symbol = "₪" } },
        { "PA", new CountryCurrency { Currency = "United States Dollar", Iso4217 = "USD", Symbol = "$" } },
        { "PG", new CountryCurrency { Currency = "Papua New Guinean Kina", Iso4217 = "PGK", Symbol = "K" } },
        { "PY", new CountryCurrency { Currency = "Paraguayan Guaraní", Iso4217 = "PYG", Symbol = "₲" } },
        { "PE", new CountryCurrency { Currency = "Peruvian Sol", Iso4217 = "PEN", Symbol = "S/." } },
        { "PH", new CountryCurrency { Currency = "Philippine Piso", Iso4217 = "PHP", Symbol = "₱" } },
        { "PN", new CountryCurrency { Currency = "New Zealand Dollar", Iso4217 = "NZD", Symbol = "$" } },
        { "PL", new CountryCurrency { Currency = "Polish Zloty", Iso4217 = "PLN", Symbol = "zł" } },
        { "PT", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "PR", new CountryCurrency { Currency = "United States Dollar", Iso4217 = "USD", Symbol = "$" } },
        { "QA", new CountryCurrency { Currency = "Qatari Riyal", Iso4217 = "QAR", Symbol = "ر.ق" } },
        { "RE", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "RO", new CountryCurrency { Currency = "Romanian Leu", Iso4217 = "RON", Symbol = "lei" } },
        { "RU", new CountryCurrency { Currency = "Russian Ruble", Iso4217 = "RUB", Symbol = "₽" } },
        { "RW", new CountryCurrency { Currency = "Rwandan Franc", Iso4217 = "RWF", Symbol = "Fr" } },
        { "SH", new CountryCurrency { Currency = "Saint Helena Pound", Iso4217 = "SHP", Symbol = "£" } },
        { "KN", new CountryCurrency { Currency = "East Caribbean Dollar", Iso4217 = "XCD", Symbol = "$" } },
        { "LC", new CountryCurrency { Currency = "East Caribbean Dollar", Iso4217 = "XCD", Symbol = "$" } },
        { "PM", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "VC", new CountryCurrency { Currency = "East Caribbean Dollar", Iso4217 = "XCD", Symbol = "$" } },
        { "BL", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "MF", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "WS", new CountryCurrency { Currency = "Samoan Tala", Iso4217 = "WST", Symbol = "T" } },
        { "SM", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "ST", new CountryCurrency { Currency = "Sao Tome And Principe Dobra", Iso4217 = "STD", Symbol = "Db" } },
        { "SA", new CountryCurrency { Currency = "Saudi Riyal", Iso4217 = "SAR", Symbol = "ر.س" } },
        { "SN", new CountryCurrency { Currency = "West African CFA Franc", Iso4217 = "XOF", Symbol = "Fr" } },
        { "RS", new CountryCurrency { Currency = "Serbian Dinar", Iso4217 = "RSD", Symbol = "дин" } },
        { "SC", new CountryCurrency { Currency = "Seychellois Rupee", Iso4217 = "SCR", Symbol = "₨" } },
        { "SL", new CountryCurrency { Currency = "Sierra Leonean Leone", Iso4217 = "SLL", Symbol = "Le" } },
        { "SG", new CountryCurrency { Currency = "Singapore Dollar", Iso4217 = "SGD", Symbol = "$" } },
        { "SX", new CountryCurrency { Currency = "Netherlands Antillean Guilder", Iso4217 = "ANG", Symbol = "ƒ" } },
        { "SK", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "SI", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "SB", new CountryCurrency { Currency = "Solomon Islands Dollar", Iso4217 = "SBD", Symbol = "$" } },
        { "SO", new CountryCurrency { Currency = "Somali Shilling", Iso4217 = "SOS", Symbol = "Sh" } },
        { "ZA", new CountryCurrency { Currency = "South African Rand", Iso4217 = "ZAR", Symbol = "R" } },
        { "GS", new CountryCurrency { Currency = "Pound Sterling", Iso4217 = "GBP", Symbol = "£" } },
        { "SS", new CountryCurrency { Currency = "South Sudanese Pound", Iso4217 = "SSP", Symbol = "£" } },
        { "ES", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "LK", new CountryCurrency { Currency = "Sri Lankan Rupee", Iso4217 = "LKR", Symbol = "Rs" } },
        { "SD", new CountryCurrency { Currency = "Sudanese Pound", Iso4217 = "SDG", Symbol = "ج.س." } },
        { "SR", new CountryCurrency { Currency = "Surinamese Dollar", Iso4217 = "SRD", Symbol = "$" } },
        { "SJ", new CountryCurrency { Currency = "Norwegian Krone", Iso4217 = "NOK", Symbol = "kr" } },
        { "SZ", new CountryCurrency { Currency = "Swazi Lilangeni", Iso4217 = "SZL", Symbol = "L" } },
        { "SE", new CountryCurrency { Currency = "Swedish Krona", Iso4217 = "SEK", Symbol = "kr" } },
        { "CH", new CountryCurrency { Currency = "Swiss Franc", Iso4217 = "CHF", Symbol = "Fr" } },
        { "SY", new CountryCurrency { Currency = "Syrian Pound", Iso4217 = "SYP", Symbol = "£S" } },
        { "TW", new CountryCurrency { Currency = "New Taiwan Dollar", Iso4217 = "TWD", Symbol = "$" } },
        { "TJ", new CountryCurrency { Currency = "Tajikistani Somoni", Iso4217 = "TJS", Symbol = "SM" } },
        { "TZ", new CountryCurrency { Currency = "Tanzanian Shilling", Iso4217 = "TZS", Symbol = "Sh" } },
        { "TH", new CountryCurrency { Currency = "Thai Baht", Iso4217 = "THB", Symbol = "฿" } },
        { "TG", new CountryCurrency { Currency = "West African CFA Franc", Iso4217 = "XOF", Symbol = "Fr" } },
        { "TK", new CountryCurrency { Currency = "New Zealand Dollar", Iso4217 = "NZD", Symbol = "$" } },
        { "TO", new CountryCurrency { Currency = "Tongan Paanga", Iso4217 = "TOP", Symbol = "T$" } },
        { "TT", new CountryCurrency { Currency = "Trinidad And Tobago Dollar", Iso4217 = "TTD", Symbol = "$" } },
        { "TN", new CountryCurrency { Currency = "Tunisian Dinar", Iso4217 = "TND", Symbol = "د.ت" } },
        { "TR", new CountryCurrency { Currency = "Turkish Lira", Iso4217 = "TRY", Symbol = "₺" } },
        { "TM", new CountryCurrency { Currency = "Turkmenistan Manat", Iso4217 = "TMT", Symbol = "m" } },
        { "TC", new CountryCurrency { Currency = "United States Dollar", Iso4217 = "USD", Symbol = "$" } },
        { "TV", new CountryCurrency { Currency = "Australian Dollar", Iso4217 = "AUD", Symbol = "$" } },
        { "UG", new CountryCurrency { Currency = "Ugandan Shilling", Iso4217 = "UGX", Symbol = "Sh" } },
        { "UA", new CountryCurrency { Currency = "Ukrainian Hryvnia", Iso4217 = "UAH", Symbol = "₴" } },
        { "AE", new CountryCurrency { Currency = "United Arab Emirates Dirham", Iso4217 = "AED", Symbol = "د.إ" } },
        { "GB", new CountryCurrency { Currency = "Pound Sterling", Iso4217 = "GBP", Symbol = "£" } },
        { "US", new CountryCurrency { Currency = "United States Dollar", Iso4217 = "USD", Symbol = "$" } },
        { "UM", new CountryCurrency { Currency = "United States Dollar", Iso4217 = "USD", Symbol = "$" } },
        { "UY", new CountryCurrency { Currency = "Uruguayan Peso", Iso4217 = "UYU", Symbol = "$" } },
        { "UZ", new CountryCurrency { Currency = "Uzbekistani Som", Iso4217 = "UZS", Symbol = "so'm" } },
        { "VU", new CountryCurrency { Currency = "Vanuatu Vatu", Iso4217 = "VUV", Symbol = "Vt" } },
        { "VA", new CountryCurrency { Currency = "Euro", Iso4217 = "EUR", Symbol = "€" } },
        { "VE", new CountryCurrency { Currency = "Venezuelan Bolívar", Iso4217 = "VEF", Symbol = "Bs" } },
        { "VN", new CountryCurrency { Currency = "Vietnamese Dong", Iso4217 = "VND", Symbol = "₫" } },
        { "VG", new CountryCurrency { Currency = "United States Dollar", Iso4217 = "USD", Symbol = "$" } },
        { "VI", new CountryCurrency { Currency = "United States Dollar", Iso4217 = "USD", Symbol = "$" } },
        { "WF", new CountryCurrency { Currency = "CFP Franc", Iso4217 = "XPF", Symbol = "Fr" } },
        { "EH", new CountryCurrency { Currency = "Algerian Dinar", Iso4217 = "DZD", Symbol = "د.ج" } },
        { "YE", new CountryCurrency { Currency = "Yemeni Rial", Iso4217 = "YER", Symbol = "﷼" } },
        { "ZM", new CountryCurrency { Currency = "Zambian Kwacha", Iso4217 = "ZMW", Symbol = "ZK" } },
        { "ZW", new CountryCurrency { Currency = "United States Dollar", Iso4217 = "USD", Symbol = "$" } },
    };
}
