using System;
using System.Collections.Generic;

namespace CountrySC;

/// <summary>
/// Static lookup of capital cities grouped by ISO 3166-1 alpha-2 country code.
/// Sourced from worlddata (https://www.worlddata.info/capital-cities.php).
/// </summary>
public static class CountryCapitals
{
    public static readonly Dictionary<string, string> Capitals = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        { "AF", "Kabul" },
        { "AX", "Mariehamn" },
        { "AL", "Tirana" },
        { "DZ", "Algiers" },
        { "AS", "Pago Pago" },
        { "AD", "Andorra la Vella" },
        { "AO", "Luanda" },
        { "AI", "The Valley" },
        { "AQ", "" },
        { "AG", "Saint John's" },
        { "AR", "Buenos Aires" },
        { "AM", "Yerevan" },
        { "AW", "Oranjestad" },
        { "AU", "Canberra" },
        { "AT", "Vienna" },
        { "AZ", "Baku" },
        { "BS", "Nassau" },
        { "BH", "Manama" },
        { "BD", "Dhaka" },
        { "BB", "Bridgetown" },
        { "BY", "Minsk" },
        { "BE", "Brussels" },
        { "BZ", "Belmopan" },
        { "BJ", "Porto-Novo" },
        { "BM", "Hamilton" },
        { "BT", "Thimphu" },
        { "BO", "Sucre" },
        { "BQ", "Kralendijk" },
        { "BA", "Sarajevo" },
        { "BW", "Gaborone" },
        { "BV", "" },
        { "BR", "Brasilia" },
        { "IO", "Diego Garcia" },
        { "BN", "Bandar Seri Begawan" },
        { "BG", "Sofia" },
        { "BF", "Ouagadougou" },
        { "BI", "Gitega" },
        { "KH", "Phnom Penh" },
        { "CM", "Yaounde" },
        { "CA", "Ottawa" },
        { "CV", "Praia" },
        { "KY", "George Town" },
        { "CF", "Bangui" },
        { "TD", "N'Djamena" },
        { "CL", "Santiago" },
        { "CN", "Beijing" },
        { "CX", "Flying Fish Cove" },
        { "CC", "West Island" },
        { "CO", "Bogota" },
        { "KM", "Moroni" },
        { "CG", "Brazzaville" },
        { "CD", "Kinshasa" },
        { "CK", "Avarua" },
        { "CR", "San José" },
        { "CI", "Yamoussoukro" },
        { "HR", "Zagreb" },
        { "CU", "Havana" },
        { "CW", "Willemstad" },
        { "CY", "Nicosia" },
        { "CZ", "Prague" },
        { "DK", "Copenhagen" },
        { "DJ", "Djibouti City" },
        { "DM", "Roseau" },
        { "DO", "Santo Domingo" },
        { "TL", "Dili" },
        { "EC", "Quito" },
        { "EG", "Cairo" },
        { "SV", "San Salvador" },
        { "GQ", "Malabo" },
        { "ER", "Asmara" },
        { "EE", "Tallinn" },
        { "ET", "Addis Ababa" },
        { "FK", "Stanley" },
        { "FO", "Tórshavn" },
        { "FJ", "Suva" },
        { "FI", "Helsinki" },
        { "FR", "Paris" },
        { "GF", "Cayenne" },
        { "PF", "Papeete" },
        { "TF", "Port-aux-Français" },
        { "GA", "Libreville" },
        { "GM", "Banjul" },
        { "GE", "Tbilisi" },
        { "DE", "Berlin" },
        { "GH", "Accra" },
        { "GI", "Gibraltar" },
        { "GR", "Athens" },
        { "GL", "Nuuk" },
        { "GD", "Saint George's" },
        { "GP", "Basse-Terre" },
        { "GU", "Hagåtña" },
        { "GT", "Guatemala City" },
        { "GG", "Saint Peter Port" },
        { "GN", "Conakry" },
        { "GW", "Bissau" },
        { "GY", "Georgetown" },
        { "HT", "Port-au-Prince" },
        { "HM", "" },
        { "HN", "Tegucigalpa" },
        { "HK", "Hong Kong" },
        { "HU", "Budapest" },
        { "IS", "Reykjavík" },
        { "IN", "New Delhi" },
        { "ID", "Jakarta" },
        { "IR", "Tehran" },
        { "IQ", "Baghdad" },
        { "IE", "Dublin" },
        { "IL", "Jerusalem" },
        { "IT", "Rome" },
        { "JM", "Kingston" },
        { "JP", "Tokyo" },
        { "JE", "Saint Helier" },
        { "JO", "Amman" },
        { "KZ", "Astana" },
        { "KE", "Nairobi" },
        { "KI", "Tarawa" },
        { "KP", "Pyongyang" },
        { "KR", "Seoul" },
        { "XK", "Pristina" },
        { "KW", "Kuwait City" },
        { "KG", "Bishkek" },
        { "LA", "Vientiane" },
        { "LV", "Riga" },
        { "LB", "Beirut" },
        { "LS", "Maseru" },
        { "LR", "Monrovia" },
        { "LY", "Tripoli" },
        { "LI", "Vaduz" },
        { "LT", "Vilnius" },
        { "LU", "Luxembourg" },
        { "MO", "Concelho de Macau" },
        { "MK", "Skopje" },
        { "MG", "Antananarivo" },
        { "MW", "Lilongwe" },
        { "MY", "Kuala Lumpur" },
        { "MV", "Malé" },
        { "ML", "Bamako" },
        { "MT", "Valletta" },
        { "IM", "Douglas" },
        { "MH", "Majuro" },
        { "MQ", "Fort-de-France" },
        { "MR", "Nouakchott" },
        { "MU", "Port Louis" },
        { "YT", "Mamoudzou" },
        { "MX", "Mexico City" },
        { "FM", "Palikir" },
        { "MD", "Chisinau" },
        { "MC", "Monaco" },
        { "MN", "Ulaanbaatar" },
        { "ME", "Podgorica" },
        { "MS", "Brades" },
        { "MA", "Rabat" },
        { "MZ", "Maputo" },
        { "MM", "Nay Pyi Taw" },
        { "NA", "Windhoek" },
        { "NR", "Yaren" },
        { "NP", "Kathmandu" },
        { "NL", "Amsterdam" },
        { "NC", "Nouméa" },
        { "NZ", "Wellington" },
        { "NI", "Managua" },
        { "NE", "Niamey" },
        { "NG", "Abuja" },
        { "NU", "Alofi" },
        { "NF", "Kingston" },
        { "MP", "Saipan" },
        { "NO", "Oslo" },
        { "OM", "Muscat" },
        { "PK", "Islamabad" },
        { "PW", "Ngerulmud" },
        { "PS", "Ramallah" },
        { "PA", "Panama City" },
        { "PG", "Port Moresby" },
        { "PY", "Asunción" },
        { "PE", "Lima" },
        { "PH", "Manila" },
        { "PN", "Adamstown" },
        { "PL", "Warsaw" },
        { "PT", "Lisbon" },
        { "PR", "San Juan" },
        { "QA", "Doha" },
        { "RE", "Saint-Denis" },
        { "RO", "Bucharest" },
        { "RU", "Moscow" },
        { "RW", "Kigali" },
        { "SH", "Jamestown" },
        { "KN", "Basseterre" },
        { "LC", "Castries" },
        { "PM", "Saint-Pierre" },
        { "VC", "Kingstown" },
        { "BL", "Gustavia" },
        { "MF", "Marigot" },
        { "WS", "Apia" },
        { "SM", "San Marino" },
        { "ST", "São Tomé" },
        { "SA", "Riyadh" },
        { "SN", "Dakar" },
        { "RS", "Belgrade" },
        { "SC", "Victoria" },
        { "SL", "Freetown" },
        { "SG", "Singapore" },
        { "SX", "Philipsburg" },
        { "SK", "Bratislava" },
        { "SI", "Ljubljana" },
        { "SB", "Honiara" },
        { "SO", "Mogadishu" },
        { "ZA", "Pretoria" },
        { "GS", "King Edward Point" },
        { "SS", "Juba" },
        { "ES", "Madrid" },
        { "LK", "Colombo" },
        { "SD", "Khartoum" },
        { "SR", "Paramaribo" },
        { "SJ", "Longyearbyen" },
        { "SZ", "Mbabane" },
        { "SE", "Stockholm" },
        { "CH", "Bern" },
        { "SY", "Damascus" },
        { "TW", "Taipei" },
        { "TJ", "Dushanbe" },
        { "TZ", "Dodoma" },
        { "TH", "Bangkok" },
        { "TG", "Lomé" },
        { "TK", "Nukunonu" },
        { "TO", "Nuku'alofa" },
        { "TT", "Port-of-Spain" },
        { "TN", "Tunis" },
        { "TR", "Ankara" },
        { "TM", "Ashgabat" },
        { "TC", "Cockburn Town" },
        { "TV", "Funafuti" },
        { "UG", "Kampala" },
        { "UA", "Kyiv" },
        { "AE", "Abu Dhabi" },
        { "GB", "London" },
        { "US", "Washington, D.C." },
        { "UM", "" },
        { "UY", "Montevideo" },
        { "UZ", "Tashkent" },
        { "VU", "Port-Vila" },
        { "VA", "Vatican City" },
        { "VE", "Caracas" },
        { "VN", "Hanoi" },
        { "VG", "Road Town" },
        { "VI", "Charlotte Amalie" },
        { "WF", "Mata-Utu" },
        { "EH", "El Aaiún" },
        { "YE", "Sanaa" },
        { "ZM", "Lusaka" },
        { "ZW", "Harare" },
    };
}
