using System;
using System.Collections.Generic;

namespace CountrySC;

/// <summary>
/// Static lookup of official language names grouped by ISO 3166-1 alpha-2 country code.
/// Sourced from Wikipedia's list of official languages by country and territory
/// (https://en.wikipedia.org/wiki/List_of_official_languages_by_country_and_territory).
/// </summary>
public static class CountryLanguages
{
    public static readonly Dictionary<string, string[]> Languages = new Dictionary<string, string[]>(StringComparer.OrdinalIgnoreCase)
    {
        { "AF", ["Persian (Dari)", "Pashto"] },
        { "AL", ["Albanian"] },
        { "DZ", ["Arabic", "Berber"] },
        { "AD", ["Catalan"] },
        { "AO", ["Portuguese"] },
        { "AG", ["(English has de facto status)", "Spanish"] },
        { "AR", ["Argentine Sign Language"] },
        { "AM", ["Armenian"] },
        { "AU", ["None (English has de facto status)"] },
        { "AT", ["German"] },
        { "AZ", ["Azerbaijani"] },
        { "BS", ["English"] },
        { "BH", ["Arabic"] },
        { "BD", ["Bengali"] },
        { "BB", ["English"] },
        { "BY", ["Belarusian", "Russian"] },
        { "BE", ["Dutch", "French", "German"] },
        { "BZ", ["English"] },
        { "BJ", ["French"] },
        { "BT", ["Dzongkha"] },
        { "BO", ["Castilian (Spanish)", "Aymara", "Araona", "Baure", "Bésiro (Chiquitano)", "Canichana", "Cavineña", "Cayubaba", "Chácobo", "Chimán", "Ese Ejja", "Guaraní", "Guarasu'we", "Guarayu", "Itonama", "Leco", "Machajuyai-Kallawaya", "Machineri", "Maropa", "Mojeño-Ignaciano", "Mojeño-Trinitario", "Moré", "Mosetén", "Movima", "Pacawara", "Puquina", "Quechua", "Sirionó", "Tacana", "Tapieté", "Toromona", "Uru-Chipaya", "Weenhayek", "Yaminawa", "Yuki", "Yuracaré", "Zamuco"] },
        { "BA", ["None (Bosnian, Croatian and Serbian all have de facto status)"] },
        { "BW", ["English"] },
        { "BR", ["Portuguese"] },
        { "BN", ["Malay"] },
        { "BG", ["Bulgarian"] },
        { "BF", ["Mooré", "Bissa", "Dyula", "Fula"] },
        { "BI", ["French", "Kirundi", "English"] },
        { "KH", ["Khmer"] },
        { "CM", ["English", "French"] },
        { "CA", ["English (Federal)", "French (Federal)"] },
        { "CV", ["Portuguese"] },
        { "CF", ["French", "Sango"] },
        { "TD", ["Arabic", "French"] },
        { "CL", ["Spanish"] },
        { "CN", ["Standard Chinese"] },
        { "CO", ["Spanish"] },
        { "KM", ["Arabic", "Comorian", "French"] },
        { "CD", ["French"] },
        { "CG", ["French"] },
        { "CK", ["English", "Cook Islands Māori"] },
        { "CR", ["Spanish"] },
        { "HR", ["Croatian"] },
        { "CU", ["Spanish"] },
        { "CY", ["Greek", "Turkish"] },
        { "CZ", ["Czech"] },
        { "DK", ["Danish"] },
        { "DJ", ["Arabic", "French"] },
        { "DM", ["English"] },
        { "DO", ["Spanish"] },
        { "TL", ["Portuguese", "Tetum"] },
        { "EC", ["Spanish"] },
        { "EG", ["Arabic"] },
        { "SV", ["Spanish"] },
        { "GQ", ["French", "Portuguese", "Spanish"] },
        { "ER", ["Tigrinya"] },
        { "EE", ["Estonian"] },
        { "SZ", ["English", "Swazi"] },
        { "ET", ["Afar", "Amharic", "Oromo", "Somali", "Tigrinya"] },
        { "FJ", ["English", "Fijian", "Fiji Hindi", "Standard Hindi"] },
        { "FI", ["Finnish", "Swedish"] },
        { "FR", ["French"] },
        { "GA", ["French"] },
        { "GM", ["English"] },
        { "GE", ["Georgian"] },
        { "DE", ["German"] },
        { "GH", ["English"] },
        { "GR", ["Greek"] },
        { "GD", ["English"] },
        { "GT", ["Spanish"] },
        { "GN", ["French"] },
        { "GW", ["Portuguese"] },
        { "GY", ["English"] },
        { "HT", ["French", "Haitian Creole"] },
        { "HN", ["Spanish"] },
        { "HK", ["Cantonese", "English"] },
        { "HU", ["Hungarian"] },
        { "IS", ["Icelandic", "Icelandic Sign Language"] },
        { "IN", ["Hindi", "English"] },
        { "ID", ["Indonesian"] },
        { "IR", ["Persian"] },
        { "IQ", ["Arabic", "Kurdish"] },
        { "IE", ["Irish", "English"] },
        { "IL", ["Hebrew"] },
        { "IT", ["Italian"] },
        { "CI", ["French"] },
        { "JM", ["English"] },
        { "JP", ["None (Japanese has de facto status)"] },
        { "JO", ["Arabic"] },
        { "KZ", ["Kazakh", "Russian"] },
        { "KE", ["English", "Swahili"] },
        { "KI", ["English", "Gilbertese"] },
        { "KP", ["Korean"] },
        { "KR", ["Korean", "Korean Sign Language"] },
        { "XK", ["Albanian", "Serbian"] },
        { "KW", ["Arabic"] },
        { "KG", ["Kyrgyz", "Russian"] },
        { "LA", ["Lao"] },
        { "LV", ["Latvian"] },
        { "LB", ["Arabic"] },
        { "LS", ["Sesotho", "English"] },
        { "LR", ["English"] },
        { "LY", ["Arabic"] },
        { "LI", ["German"] },
        { "LT", ["Lithuanian"] },
        { "LU", ["French", "German", "Luxembourgish"] },
        { "MO", ["Cantonese", "Portuguese"] },
        { "MG", ["French", "Malagasy"] },
        { "MW", ["English"] },
        { "MY", ["Malay"] },
        { "MV", ["Dhivehi"] },
        { "ML", ["Bambara", "Bobo", "Bozo", "Dogon", "Fula", "Hassaniya", "Kassonke", "Maninke", "Minyanka", "Senufo", "Songhay", "Soninke", "Tamasheq"] },
        { "MT", ["Maltese", "English"] },
        { "MH", ["English", "Marshallese"] },
        { "MR", ["Arabic"] },
        { "MU", ["None (English and French have de facto status)"] },
        { "MX", ["None (Spanish has de facto status)"] },
        { "FM", ["English"] },
        { "MD", ["Romanian"] },
        { "MC", ["French"] },
        { "MN", ["Mongolian"] },
        { "ME", ["Montenegrin"] },
        { "MA", ["Arabic", "Berber"] },
        { "MZ", ["Portuguese"] },
        { "MM", ["Burmese"] },
        { "NA", ["English"] },
        { "NR", ["English", "Nauruan"] },
        { "NP", ["Nepali"] },
        { "NL", ["Dutch"] },
        { "NZ", ["Māori language", "New Zealand Sign Language", "(English has de facto status)"] },
        { "NI", ["Spanish"] },
        { "NE", ["Hausa"] },
        { "NG", ["English"] },
        { "NU", ["English", "Niuean"] },
        { "MK", ["Macedonian", "Albanian"] },
        { "NO", ["Norwegian", "Sami"] },
        { "OM", ["Arabic"] },
        { "PK", ["Urdu", "English"] },
        { "PW", ["English", "Palauan"] },
        { "PS", ["Arabic"] },
        { "PA", ["Spanish"] },
        { "PG", ["English", "Hiri Motu", "PNG Sign Language", "Tok Pisin"] },
        { "PY", ["Spanish", "Guaraní"] },
        { "PE", ["Spanish"] },
        { "PH", ["Filipino", "English"] },
        { "PL", ["Polish"] },
        { "PT", ["Portuguese"] },
        { "QA", ["Arabic"] },
        { "RO", ["Romanian"] },
        { "RU", ["Russian"] },
        { "RW", ["English", "French", "Kinyarwanda", "Swahili"] },
        { "KN", ["English"] },
        { "LC", ["English"] },
        { "VC", ["English"] },
        { "WS", ["English", "Samoan"] },
        { "SM", ["Italian"] },
        { "ST", ["Portuguese"] },
        { "SA", ["Arabic"] },
        { "SN", ["French"] },
        { "RS", ["Serbian"] },
        { "SC", ["English", "French", "Seychellois Creole"] },
        { "SL", ["English"] },
        { "SG", ["English", "Malay", "Mandarin Chinese", "Tamil"] },
        { "SK", ["Slovak"] },
        { "SI", ["Slovene"] },
        { "SB", ["English"] },
        { "SO", ["Somali", "Arabic"] },
        { "ZA", ["Afrikaans", "English", "Southern Ndebele", "Sotho", "Northern Sotho", "Swazi", "Tsonga", "Tswana", "Venda", "Xhosa", "Zulu", "SA Sign Language"] },
        { "SS", ["English"] },
        { "ES", ["Spanish"] },
        { "LK", ["Sinhala", "Tamil"] },
        { "SD", ["Arabic", "English"] },
        { "SR", ["Dutch"] },
        { "SE", ["Swedish"] },
        { "CH", ["French (Bern, Fribourg, Geneva, Jura, Neuchâtel, Valais, Vaud)", "German (Aargau, Appenzell Ausserrhoden, Appenzell Innerrhoden, Basel-Landschaft, Basel-Stadt, Bern, Fribourg, Glarus, Graubünden, Lucerne, Nidwalden, Obwalden, Saint Gallen, Schaffhausen, Schwyz, Solothurn, Thurgau, Uri, Valais, Zug, Zürich)", "Italian (Ticino, Graubünden)", "Romansh (Graubünden)"] },
        { "SY", ["Arabic"] },
        { "TW", ["None (Mandarin Chinese has de facto status)"] },
        { "TJ", ["Tajik"] },
        { "TZ", ["Swahili", "English"] },
        { "TH", ["Thai"] },
        { "TG", ["French"] },
        { "TO", ["English", "Tongan"] },
        { "TT", ["English"] },
        { "TN", ["Arabic"] },
        { "TR", ["Turkish"] },
        { "TM", ["Turkmen"] },
        { "TV", ["Tuvaluan", "English"] },
        { "UG", ["English", "Swahili"] },
        { "UA", ["Ukrainian"] },
        { "AE", ["Arabic"] },
        { "GB", ["None (English has de facto status)"] },
        { "US", ["None (English has de facto status)"] },
        { "UY", ["(Spanish has de facto status)", "Uruguayan Sign Language"] },
        { "UZ", ["Uzbek"] },
        { "VU", ["English", "French", "Bislama"] },
        { "VA", ["Italian", "Latin"] },
        { "VE", ["Spanish"] },
        { "VN", ["Vietnamese"] },
        { "YE", ["Arabic"] },
        { "ZM", ["English"] },
        { "ZW", ["Chewa", "Chibarwe", "English", "Kalanga", "Khoisan", "Nambya", "Ndau", "Ndebele", "Shangani", "Shona", "Sign language", "Sotho", "Tonga", "Tswana", "Venda", "Xhosa"] },
    };
}
