using System;
using System.Collections.Generic;

namespace CountrySC;

/// <summary>
/// Static lookup of IANA time zone identifiers grouped by ISO 3166-1 alpha-2 country code.
/// Sourced from the TimeZoneDB time zone list (https://timezonedb.com/time-zones).
/// </summary>
public static class CountryTimeZones
{
    public static readonly Dictionary<string, string[]> Zones = new Dictionary<string, string[]>(StringComparer.OrdinalIgnoreCase)
    {
        { "AF", ["Asia/Kabul"] },
        { "AL", ["Europe/Tirane"] },
        { "DZ", ["Africa/Algiers"] },
        { "AS", ["Pacific/Pago_Pago"] },
        { "AD", ["Europe/Andorra"] },
        { "AO", ["Africa/Luanda"] },
        { "AI", ["America/Anguilla"] },
        { "AQ", ["Antarctica/Casey", "Antarctica/Davis", "Antarctica/DumontDUrville", "Antarctica/Mawson", "Antarctica/McMurdo", "Antarctica/Palmer", "Antarctica/Rothera", "Antarctica/Syowa", "Antarctica/Troll", "Antarctica/Vostok"] },
        { "AG", ["America/Antigua"] },
        { "AR", ["America/Argentina/Buenos_Aires", "America/Argentina/Catamarca", "America/Argentina/Cordoba", "America/Argentina/Jujuy", "America/Argentina/La_Rioja", "America/Argentina/Mendoza", "America/Argentina/Rio_Gallegos", "America/Argentina/Salta", "America/Argentina/San_Juan", "America/Argentina/San_Luis", "America/Argentina/Tucuman", "America/Argentina/Ushuaia"] },
        { "AM", ["Asia/Yerevan"] },
        { "AW", ["America/Aruba"] },
        { "AU", ["Antarctica/Macquarie", "Australia/Adelaide", "Australia/Brisbane", "Australia/Broken_Hill", "Australia/Darwin", "Australia/Eucla", "Australia/Hobart", "Australia/Lindeman", "Australia/Lord_Howe", "Australia/Melbourne", "Australia/Perth", "Australia/Sydney"] },
        { "AT", ["Europe/Vienna"] },
        { "AZ", ["Asia/Baku"] },
        { "BS", ["America/Nassau"] },
        { "BH", ["Asia/Bahrain"] },
        { "BD", ["Asia/Dhaka"] },
        { "BB", ["America/Barbados"] },
        { "BY", ["Europe/Minsk"] },
        { "BE", ["Europe/Brussels"] },
        { "BZ", ["America/Belize"] },
        { "BJ", ["Africa/Porto-Novo"] },
        { "BM", ["Atlantic/Bermuda"] },
        { "BT", ["Asia/Thimphu"] },
        { "BO", ["America/La_Paz"] },
        { "BQ", ["America/Kralendijk"] },
        { "BA", ["Europe/Sarajevo"] },
        { "BW", ["Africa/Gaborone"] },
        { "BR", ["America/Araguaina", "America/Bahia", "America/Belem", "America/Boa_Vista", "America/Campo_Grande", "America/Cuiaba", "America/Eirunepe", "America/Fortaleza", "America/Maceio", "America/Manaus", "America/Noronha", "America/Porto_Velho", "America/Recife", "America/Rio_Branco", "America/Santarem", "America/Sao_Paulo"] },
        { "IO", ["Indian/Chagos"] },
        { "BN", ["Asia/Brunei"] },
        { "BG", ["Europe/Sofia"] },
        { "BF", ["Africa/Ouagadougou"] },
        { "BI", ["Africa/Bujumbura"] },
        { "KH", ["Asia/Phnom_Penh"] },
        { "CM", ["Africa/Douala"] },
        { "CA", ["America/Atikokan", "America/Blanc-Sablon", "America/Cambridge_Bay", "America/Creston", "America/Dawson", "America/Dawson_Creek", "America/Edmonton", "America/Fort_Nelson", "America/Glace_Bay", "America/Goose_Bay", "America/Halifax", "America/Inuvik", "America/Iqaluit", "America/Moncton", "America/Rankin_Inlet", "America/Regina", "America/Resolute", "America/St_Johns", "America/Swift_Current", "America/Toronto", "America/Vancouver", "America/Whitehorse", "America/Winnipeg"] },
        { "CV", ["Atlantic/Cape_Verde"] },
        { "KY", ["America/Cayman"] },
        { "CF", ["Africa/Bangui"] },
        { "TD", ["Africa/Ndjamena"] },
        { "CL", ["America/Coyhaique", "America/Punta_Arenas", "America/Santiago", "Pacific/Easter"] },
        { "CN", ["Asia/Shanghai", "Asia/Urumqi"] },
        { "CX", ["Indian/Christmas"] },
        { "CC", ["Indian/Cocos"] },
        { "CO", ["America/Bogota"] },
        { "KM", ["Indian/Comoro"] },
        { "CG", ["Africa/Brazzaville"] },
        { "CD", ["Africa/Kinshasa", "Africa/Lubumbashi"] },
        { "CK", ["Pacific/Rarotonga"] },
        { "CR", ["America/Costa_Rica"] },
        { "HR", ["Europe/Zagreb"] },
        { "CU", ["America/Havana"] },
        { "CW", ["America/Curacao"] },
        { "CY", ["Asia/Famagusta", "Asia/Nicosia"] },
        { "CZ", ["Europe/Prague"] },
        { "CI", ["Africa/Abidjan"] },
        { "DK", ["Europe/Copenhagen"] },
        { "DJ", ["Africa/Djibouti"] },
        { "DM", ["America/Dominica"] },
        { "DO", ["America/Santo_Domingo"] },
        { "EC", ["America/Guayaquil", "Pacific/Galapagos"] },
        { "EG", ["Africa/Cairo"] },
        { "SV", ["America/El_Salvador"] },
        { "GQ", ["Africa/Malabo"] },
        { "ER", ["Africa/Asmara"] },
        { "EE", ["Europe/Tallinn"] },
        { "ET", ["Africa/Addis_Ababa"] },
        { "FK", ["Atlantic/Stanley"] },
        { "FO", ["Atlantic/Faroe"] },
        { "FJ", ["Pacific/Fiji"] },
        { "FI", ["Europe/Helsinki"] },
        { "FR", ["Europe/Paris"] },
        { "GF", ["America/Cayenne"] },
        { "PF", ["Pacific/Gambier", "Pacific/Marquesas", "Pacific/Tahiti"] },
        { "TF", ["Indian/Kerguelen"] },
        { "GA", ["Africa/Libreville"] },
        { "GM", ["Africa/Banjul"] },
        { "GE", ["Asia/Tbilisi"] },
        { "DE", ["Europe/Berlin", "Europe/Busingen"] },
        { "GH", ["Africa/Accra"] },
        { "GI", ["Europe/Gibraltar"] },
        { "GR", ["Europe/Athens"] },
        { "GL", ["America/Danmarkshavn", "America/Nuuk", "America/Scoresbysund", "America/Thule"] },
        { "GD", ["America/Grenada"] },
        { "GP", ["America/Guadeloupe"] },
        { "GU", ["Pacific/Guam"] },
        { "GT", ["America/Guatemala"] },
        { "GG", ["Europe/Guernsey"] },
        { "GN", ["Africa/Conakry"] },
        { "GW", ["Africa/Bissau"] },
        { "GY", ["America/Guyana"] },
        { "HT", ["America/Port-au-Prince"] },
        { "VA", ["Europe/Vatican"] },
        { "HN", ["America/Tegucigalpa"] },
        { "HK", ["Asia/Hong_Kong"] },
        { "HU", ["Europe/Budapest"] },
        { "IS", ["Atlantic/Reykjavik"] },
        { "IN", ["Asia/Kolkata"] },
        { "ID", ["Asia/Jakarta", "Asia/Jayapura", "Asia/Makassar", "Asia/Pontianak"] },
        { "IR", ["Asia/Tehran"] },
        { "IQ", ["Asia/Baghdad"] },
        { "IE", ["Europe/Dublin"] },
        { "IM", ["Europe/Isle_of_Man"] },
        { "IL", ["Asia/Jerusalem"] },
        { "IT", ["Europe/Rome"] },
        { "JM", ["America/Jamaica"] },
        { "JP", ["Asia/Tokyo"] },
        { "JE", ["Europe/Jersey"] },
        { "JO", ["Asia/Amman"] },
        { "KZ", ["Asia/Almaty", "Asia/Aqtau", "Asia/Aqtobe", "Asia/Atyrau", "Asia/Oral", "Asia/Qostanay", "Asia/Qyzylorda"] },
        { "KE", ["Africa/Nairobi"] },
        { "KI", ["Pacific/Kanton", "Pacific/Kiritimati", "Pacific/Tarawa"] },
        { "KP", ["Asia/Pyongyang"] },
        { "KR", ["Asia/Seoul"] },
        { "KW", ["Asia/Kuwait"] },
        { "KG", ["Asia/Bishkek"] },
        { "LA", ["Asia/Vientiane"] },
        { "LV", ["Europe/Riga"] },
        { "LB", ["Asia/Beirut"] },
        { "LS", ["Africa/Maseru"] },
        { "LR", ["Africa/Monrovia"] },
        { "LY", ["Africa/Tripoli"] },
        { "LI", ["Europe/Vaduz"] },
        { "LT", ["Europe/Vilnius"] },
        { "LU", ["Europe/Luxembourg"] },
        { "MO", ["Asia/Macau"] },
        { "MK", ["Europe/Skopje"] },
        { "MG", ["Indian/Antananarivo"] },
        { "MW", ["Africa/Blantyre"] },
        { "MY", ["Asia/Kuala_Lumpur", "Asia/Kuching"] },
        { "MV", ["Indian/Maldives"] },
        { "ML", ["Africa/Bamako"] },
        { "MT", ["Europe/Malta"] },
        { "MH", ["Pacific/Kwajalein", "Pacific/Majuro"] },
        { "MQ", ["America/Martinique"] },
        { "MR", ["Africa/Nouakchott"] },
        { "MU", ["Indian/Mauritius"] },
        { "YT", ["Indian/Mayotte"] },
        { "MX", ["America/Bahia_Banderas", "America/Cancun", "America/Chihuahua", "America/Ciudad_Juarez", "America/Hermosillo", "America/Matamoros", "America/Mazatlan", "America/Merida", "America/Mexico_City", "America/Monterrey", "America/Ojinaga", "America/Tijuana"] },
        { "FM", ["Pacific/Chuuk", "Pacific/Kosrae", "Pacific/Pohnpei"] },
        { "MD", ["Europe/Chisinau"] },
        { "MC", ["Europe/Monaco"] },
        { "MN", ["Asia/Hovd", "Asia/Ulaanbaatar"] },
        { "ME", ["Europe/Podgorica"] },
        { "MS", ["America/Montserrat"] },
        { "MA", ["Africa/Casablanca", "Africa/El_Aaiun"] },
        { "MZ", ["Africa/Maputo"] },
        { "MM", ["Asia/Yangon"] },
        { "NA", ["Africa/Windhoek"] },
        { "NR", ["Pacific/Nauru"] },
        { "NP", ["Asia/Kathmandu"] },
        { "NL", ["Europe/Amsterdam"] },
        { "NC", ["Pacific/Noumea"] },
        { "NZ", ["Pacific/Auckland", "Pacific/Chatham"] },
        { "NI", ["America/Managua"] },
        { "NE", ["Africa/Niamey"] },
        { "NG", ["Africa/Lagos"] },
        { "NU", ["Pacific/Niue"] },
        { "NF", ["Pacific/Norfolk"] },
        { "MP", ["Pacific/Saipan"] },
        { "NO", ["Europe/Oslo"] },
        { "OM", ["Asia/Muscat"] },
        { "PK", ["Asia/Karachi"] },
        { "PW", ["Pacific/Palau"] },
        { "PS", ["Asia/Gaza", "Asia/Hebron"] },
        { "PA", ["America/Panama"] },
        { "PG", ["Pacific/Bougainville", "Pacific/Port_Moresby"] },
        { "PY", ["America/Asuncion"] },
        { "PE", ["America/Lima"] },
        { "PH", ["Asia/Manila"] },
        { "PN", ["Pacific/Pitcairn"] },
        { "PL", ["Europe/Warsaw"] },
        { "PT", ["Atlantic/Azores", "Atlantic/Madeira", "Europe/Lisbon"] },
        { "PR", ["America/Puerto_Rico"] },
        { "QA", ["Asia/Qatar"] },
        { "RO", ["Europe/Bucharest"] },
        { "RU", ["Asia/Anadyr", "Asia/Barnaul", "Asia/Chita", "Asia/Irkutsk", "Asia/Kamchatka", "Asia/Khandyga", "Asia/Krasnoyarsk", "Asia/Magadan", "Asia/Novokuznetsk", "Asia/Novosibirsk", "Asia/Omsk", "Asia/Sakhalin", "Asia/Srednekolymsk", "Asia/Tomsk", "Asia/Ust-Nera", "Asia/Vladivostok", "Asia/Yakutsk", "Asia/Yekaterinburg", "Europe/Astrakhan", "Europe/Kaliningrad", "Europe/Kirov", "Europe/Moscow", "Europe/Samara", "Europe/Saratov", "Europe/Ulyanovsk", "Europe/Volgograd"] },
        { "RW", ["Africa/Kigali"] },
        { "RE", ["Indian/Reunion"] },
        { "BL", ["America/St_Barthelemy"] },
        { "SH", ["Atlantic/St_Helena"] },
        { "KN", ["America/St_Kitts"] },
        { "LC", ["America/St_Lucia"] },
        { "MF", ["America/Marigot"] },
        { "PM", ["America/Miquelon"] },
        { "VC", ["America/St_Vincent"] },
        { "WS", ["Pacific/Apia"] },
        { "SM", ["Europe/San_Marino"] },
        { "ST", ["Africa/Sao_Tome"] },
        { "SA", ["Asia/Riyadh"] },
        { "SN", ["Africa/Dakar"] },
        { "RS", ["Europe/Belgrade"] },
        { "SC", ["Indian/Mahe"] },
        { "SL", ["Africa/Freetown"] },
        { "SG", ["Asia/Singapore"] },
        { "SX", ["America/Lower_Princes"] },
        { "SK", ["Europe/Bratislava"] },
        { "SI", ["Europe/Ljubljana"] },
        { "SB", ["Pacific/Guadalcanal"] },
        { "SO", ["Africa/Mogadishu"] },
        { "ZA", ["Africa/Johannesburg"] },
        { "GS", ["Atlantic/South_Georgia"] },
        { "SS", ["Africa/Juba"] },
        { "ES", ["Africa/Ceuta", "Atlantic/Canary", "Europe/Madrid"] },
        { "LK", ["Asia/Colombo"] },
        { "SD", ["Africa/Khartoum"] },
        { "SR", ["America/Paramaribo"] },
        { "SJ", ["Arctic/Longyearbyen"] },
        { "SZ", ["Africa/Mbabane"] },
        { "SE", ["Europe/Stockholm"] },
        { "CH", ["Europe/Zurich"] },
        { "SY", ["Asia/Damascus"] },
        { "TW", ["Asia/Taipei"] },
        { "TJ", ["Asia/Dushanbe"] },
        { "TZ", ["Africa/Dar_es_Salaam"] },
        { "TH", ["Asia/Bangkok"] },
        { "TL", ["Asia/Dili"] },
        { "TG", ["Africa/Lome"] },
        { "TK", ["Pacific/Fakaofo"] },
        { "TO", ["Pacific/Tongatapu"] },
        { "TT", ["America/Port_of_Spain"] },
        { "TN", ["Africa/Tunis"] },
        { "TR", ["Europe/Istanbul"] },
        { "TM", ["Asia/Ashgabat"] },
        { "TC", ["America/Grand_Turk"] },
        { "TV", ["Pacific/Funafuti"] },
        { "UG", ["Africa/Kampala"] },
        { "UA", ["Europe/Kyiv", "Europe/Simferopol"] },
        { "AE", ["Asia/Dubai"] },
        { "GB", ["Europe/London"] },
        { "US", ["America/Adak", "America/Anchorage", "America/Boise", "America/Chicago", "America/Denver", "America/Detroit", "America/Indiana/Indianapolis", "America/Indiana/Knox", "America/Indiana/Marengo", "America/Indiana/Petersburg", "America/Indiana/Tell_City", "America/Indiana/Vevay", "America/Indiana/Vincennes", "America/Indiana/Winamac", "America/Juneau", "America/Kentucky/Louisville", "America/Kentucky/Monticello", "America/Los_Angeles", "America/Menominee", "America/Metlakatla", "America/New_York", "America/Nome", "America/North_Dakota/Beulah", "America/North_Dakota/Center", "America/North_Dakota/New_Salem", "America/Phoenix", "America/Sitka", "America/Yakutat", "Pacific/Honolulu"] },
        { "UM", ["Pacific/Midway", "Pacific/Wake"] },
        { "UY", ["America/Montevideo"] },
        { "UZ", ["Asia/Samarkand", "Asia/Tashkent"] },
        { "VU", ["Pacific/Efate"] },
        { "VE", ["America/Caracas"] },
        { "VN", ["Asia/Ho_Chi_Minh"] },
        { "VG", ["America/Tortola"] },
        { "VI", ["America/St_Thomas"] },
        { "WF", ["Pacific/Wallis"] },
        { "YE", ["Asia/Aden"] },
        { "ZM", ["Africa/Lusaka"] },
        { "ZW", ["Africa/Harare"] },
        { "AX", ["Europe/Mariehamn"] },
    };
}
